angular.module('clever.management.filters.typemap', []).filter('typemap', function() {


  var typeMap = {

    'DV_INTERVAL': 'interval',
    'DV_INTERVAL<DV_DATE>': 'interval_datetime',
    'DV_INTERVAl<DV_TIME>': 'interval_datetime',
    'DV_INTERVAL<DV_DATE_TIME>': 'interval_datetime',
    'DV_INTERVAL<COUNT>': 'interval_count',
    'DV_INTERVAL<DV_COUNT>': 'interval_count',
    'DV_INTERVAL<QUANTITY>': 'interval_quantity',
    'DV_INTERVAL<DV_QUANTITY>': 'interval_quantity',
    'CHOICE': 'choice',

    'ELEMENT': 'element',

    'INTERVAL_COUNT': 'interval_count',
    'INTERVAL_QUANTITY': 'interval_quantity',
    'INTERVAL_DATETIME': 'interval_datetime',

    'SLOT': 'slot',
    'SLOT_CLUSTER': 'slot_cluster',
    'SLOT_ELEMENT': 'slot_element',
    'SLOT_ITEM': 'slot',


    'ITEM_TABLE': 'structure',
    'ITEM_SINGLE': 'structure',
    'ITEM_LIST': 'structure',
    'ITEM_TREE': 'structure',
    'PARTY_INDENTITY': 'party_identity',
    'ANDDRESS': 'address',
    'PARTY_RELATIONSHIP': 'party_relationship',
    'CAPABILITY': 'capability',
    'ORGANISATION': 'organisation',
    'ORGANIZATION': 'organisation',
    'CONTACT': 'contact',
    'PERSON': 'demographic',
    'ROLE': 'role',
    'ADMIN_ENTRY': 'admin',
    'PARTICIPATION': 'participation',

    'PATHABLE': 'pathable',
    'LOCATABLE': 'locatable',
    'LINK': 'link',
    'PARTY_PROXY': '',
    'PARTY_SELF': '',
    'PARTY_IDENTIFIED': 'party_identity',
    'PARTY_RELATED': 'party_related',
    'PARTICIPATION': 'participation',
    'AUDIT_DETAILS': 'audit_details',
    //'DATA_VALUE': 'aata Value',
    'DV_BOOLEAN': 'truefalse',
    'DV_STATE': 'state',
    'DV_IDENTIFIER': 'id',
    'DV_TEXT': 'text',
    //'CODE_PHRASE': 'code Phase',
    'DV_CODED_TEXT': 'text',
    'DV_PARAGRAPH': 'paragraph',
    'DV_ORDINAL': 'ordinal',
    'C_DV_QUANTITY': 'quantity',
    //'C_QUANTITY_ITEM': 'quantity',
    'C_DV_ORDINAL': 'ordinal',
    'DV_COUNT': 'count',
    'DV_PROPORTION': 'ratio',
    'DV_DATE': 'datetime',
    'DV_TIME': 'datetime',
    'DV_DATE_TIME': 'datetime',
    'DV_DURATION': 'duration',
    'DV_ENCAPSULATED': 'encapsulated',
    'DV_MULTIMEDIA': 'multimedia',
    'DV_PARSABLE': 'parsable',
    'DV_URI': 'uri',
    'DV_EHR_URI': 'uri',
    //'DATA_STRUCTURE': 'Data Structure',
    //  'ITEM_STRUCTURE': 'Item Structure',

    'ITEM_TABLE': 'structure',
    'ITEM_SINGLE': 'structure',
    'ITEM_LIST': 'structure',
    'ITEM_TREE': 'structure',
    //  'ITEM': 'Item',
    'CLUSTER': 'cluster',
    'ELEMENT': 'element',
    'HISTORY': 'history',
    'EVENT': 'any',
    'POINT_EVENT': 'pointintime',
    'INTERVAL_EVENT': 'interval',
    'UID': 'id',
    'ISO_ID': 'id',
    'UUID': 'id',
    'INTERNET_ID': 'id',
    'OBJECT_ID': 'id',
    'UID_BASE_ID': 'id',
    'HIER_OBJECT_ID': 'id',
    'OBJECT_VERSION_ID': 'id',
    'VERSION_TREE_ID': 'id',
    'ARCHETYPE_ID': 'id',
    'TERMINOLOGY_ID': 'id',
    'GENERIC_ID': 'id',
    'OBJECT_REF': 'ref',
    //  'CCESS_GROUP_REF': 'CCESS_GROUP_REF',
    'PARTY_REF': 'ref',
    //  'LOCATABLE_REF': 'Locatable Reference',
    'PARTY': 'party',
    'PARTY_IDENTITY': 'party_identity',
    'CONTACT': 'concat',
    'ADDRESS': 'address',
    'ACTOR': 'actor',
    'PERSON': 'person',
    'ORGANISATION': 'organisation',
    'GROUP': 'group',
    'AGENT': 'agent',
    'ROLE': 'role',
    'CAPABILITY': 'capability',
    'PARTY_RELATIONSHIP': 'party_relationship',
    'CONTENT_ITEM': 'content_item',
    'EVENT_CONTEXT': 'event_context',
    'COMPOSITION': 'composition',
    'SECTION': 'section',
    'ENTRY': 'entry',
    'ADMIN_ENTRY': 'admin_entry',
    'CARE_ENTRY': 'care_entry',
    'OBSERVATION': 'observation',
    'EVALUATION': 'evaluation',
    'INSTRUCTION': 'instruction',
    'ACTIVITY': 'activity',
    'ACTION': 'action',
    //'INSTRUCTION_DETAILS': 'instruction Details',
    'ISM_TRANSITION': 'transition',
  };

  return function(input) {
    return typeMap[input] ? typeMap[input] : input;
  };
});
